services:
  speech-portal:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ..:/repo
      - ./backend:/app
    restart: unless-stopped
